---
- name: Configure kubectl for eks
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update kubeconfig for wanderlust eks cluster
      ansible.builtin.command:
        cmd: aws eks update-kubeconfig --region ap-south-1 --name wanderlust-cluster
      become_user: ubuntu
